CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    type        VARCHAR(50) NOT NULL,
    description TEXT,
    volume_ml   INTEGER NOT NULL CHECK (volume_ml > 0),
    price       NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    active      BOOLEAN NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_product_name_lower
    ON product (LOWER(name));

CREATE INDEX idx_product_active
    ON product (active);
