CREATE TABLE batch
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT NOT NULL REFERENCES product(id),
    lot_number        VARCHAR(100) NOT NULL,
    received_quantity INTEGER NOT NULL CHECK (received_quantity > 0),
    quantity_on_hand  INTEGER NOT NULL CHECK (quantity_on_hand >= 0),
    quantity_reserved INTEGER NOT NULL CHECK (quantity_reserved >= 0 AND quantity_reserved <= quantity_on_hand),
    received_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_on        DATE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_batch_expiration CHECK (expires_on IS NULL OR expires_on >= (received_at AT TIME ZONE 'UTC')::date)
);

CREATE UNIQUE INDEX uq_batch_product_lot_active
    ON batch (product_id, LOWER(lot_number))
    WHERE deleted_at IS NULL;

CREATE INDEX idx_batch_product ON batch(product_id);
CREATE INDEX idx_batch_fefo ON batch(product_id, expires_on, received_at) WHERE deleted_at IS NULL;

CREATE TABLE stock_movement
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    BIGINT NOT NULL REFERENCES batch(id),
    type        VARCHAR(30) NOT NULL,
    quantity    INTEGER NOT NULL CHECK (quantity > 0),
    reference   VARCHAR(150),
    note        TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_stock_movement_batch_date ON stock_movement(batch_id, occurred_at, id);

CREATE TABLE allocation
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_line_id BIGINT NOT NULL,
    batch_id      BIGINT NOT NULL REFERENCES batch(id),
    quantity      INTEGER NOT NULL CHECK (quantity > 0),
    status        VARCHAR(20) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_allocation_order_line ON allocation(order_line_id);
CREATE INDEX idx_allocation_batch ON allocation(batch_id);
