CREATE TABLE customer_order
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number       VARCHAR(80) NOT NULL,
    customer_reference VARCHAR(150),
    status             VARCHAR(20) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at         TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uq_customer_order_number
    ON customer_order(order_number);

CREATE INDEX idx_customer_order_status
    ON customer_order(status)
    WHERE deleted_at IS NULL;

CREATE TABLE order_line
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL REFERENCES customer_order(id),
    product_id   BIGINT NOT NULL REFERENCES product(id),
    product_name VARCHAR(150) NOT NULL,
    quantity     INTEGER NOT NULL CHECK (quantity > 0),
    unit_price   NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_order_line_order ON order_line(order_id);
CREATE INDEX idx_order_line_product ON order_line(product_id);

ALTER TABLE allocation
    ADD CONSTRAINT fk_allocation_order_line
        FOREIGN KEY (order_line_id) REFERENCES order_line(id);
