CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254) NOT NULL,
    display_name  VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL,
    enabled       BOOLEAN NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at    TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uq_app_user_email_active
    ON app_user (LOWER(email))
    WHERE deleted_at IS NULL;

CREATE INDEX idx_app_user_role
    ON app_user(role)
    WHERE deleted_at IS NULL;

CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES app_user(id),
    token_hash  CHAR(64) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uq_refresh_token_hash
    ON refresh_token(token_hash);

CREATE INDEX idx_refresh_token_user_active
    ON refresh_token(user_id, expires_at)
    WHERE revoked_at IS NULL;
